//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shinup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestation()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int IdPrestation { get; set; }
        public string NomPrestation { get; set; }
        public string PhotoPrestation { get; set; }
        public int IdTypePrestation { get; set; }
        public string DescriptionPrestation { get; set; }
        public Nullable<decimal> PrixDeBasePrestation { get; set; }
        public bool EtatPrestation { get; set; }
    
        public virtual TypePrestation TypePrestation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
